import type { Theme, ThemeName } from '../types';

export const themes: Record<ThemeName, Theme> = {
  light: {
    name: 'Light',
    classes: {
      appBg: 'bg-gray-100',
      headerBg: 'bg-white',
      cardBg: 'bg-white/50',
      cardBorder: 'border-gray-200',
      textHeading: 'text-black',
      textColor: 'text-dark',
      textAccent: 'text-primary',
      textMuted: 'text-gray-500',
      buttonBg: 'bg-primary',
      buttonHoverBg: 'hover:bg-primary-dark',
      buttonRing: 'focus:ring-primary',
      buttonFocusRingOffset: 'focus:ring-offset-gray-100',
      navButtonActiveBg: 'bg-primary',
      navButtonHoverBg: 'hover:bg-gray-200',
      inputBg: 'bg-light',
      inputText: 'text-dark',
      inputBorder: 'border-medium',
      placeholderText: 'placeholder:text-muted',
    },
  },
  dark: {
    name: 'Dark',
    classes: {
      appBg: 'bg-gray-900',
      headerBg: 'bg-gray-800',
      cardBg: 'bg-gray-800/50',
      cardBorder: 'border-gray-700',
      textHeading: 'text-white',
      textColor: 'text-gray-300',
      textAccent: 'text-primary',
      textMuted: 'text-gray-400',
      buttonBg: 'bg-primary',
      buttonHoverBg: 'hover:bg-primary-dark',
      buttonRing: 'focus:ring-primary',
      buttonFocusRingOffset: 'focus:ring-offset-gray-800',
      navButtonActiveBg: 'bg-primary',
      navButtonHoverBg: 'hover:bg-gray-600',
      inputBg: 'bg-gray-700',
      inputText: 'text-white',
      inputBorder: 'border-gray-600',
      placeholderText: 'placeholder:text-gray-400',
    },
  },
  evergreen: {
    name: 'Evergreen',
    classes: {
      appBg: 'bg-green-900',
      headerBg: 'bg-green-800',
      cardBg: 'bg-green-800/50',
      cardBorder: 'border-green-700',
      textHeading: 'text-white',
      textColor: 'text-green-100',
      textAccent: 'text-primary',
      textMuted: 'text-green-300',
      buttonBg: 'bg-primary',
      buttonHoverBg: 'hover:bg-primary-dark',
      buttonRing: 'focus:ring-primary',
      buttonFocusRingOffset: 'focus:ring-offset-green-900',
      navButtonActiveBg: 'bg-primary',
      navButtonHoverBg: 'hover:bg-green-700',
      inputBg: 'bg-green-800',
      inputText: 'text-white',
      inputBorder: 'border-green-600',
      placeholderText: 'placeholder:text-green-300',
    },
  },
};